server:
  port: 8081
  servlet:
    context-path: /api
spring:
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  autoconfigure:
    exclude:
      - org.springframework.cloud.sleuth.autoconfig.instrument.async.TraceAsyncCustomAutoConfiguration